### ISSUE TITLE
Add rss feed as notification option

### ISSUE THREAD

**Issue by git-sid** [ticketfrei/ticketfrei#54]
Mastodon is able to display toots as an rss feed. E. g. https://chaos.social/users/nbg_ticketfrei.atom

Adding that info to the description text may be a good idea.

**Comment by b3yond** [comment]
should be added to the default city page :) it's in markdown at the bottom of user.py

**Comment by git-sid** [comment]
please review and check commit 9508618347baf2d6e878321cd86d2563588c3542 for errors before closing the issue.

**Comment by git-sid** [comment]
fixed with commit 7cb211b4cb7de1116c97e4afd6739ca48405f9aa.
