### ISSUE TITLE
change banner image on social media instances

### ISSUE THREAD

**Issue by git-sid** [ticketfrei/ticketfrei#56]
Many reviewers pointed out that the banner image is ridiculous.
Furthermore, a few were offended by the crossed out hindu/buddhist symbol.
I would suggest changing the banner to a more neutral image that isn't offensive nor polemic.

**Comment by b3yond** [comment]
I disagree.

Also a crossed out swastika offends exactly the right people imho.

But let's discuss this face2face :)

**Comment by b3yond** [comment]
Do you have an alternative proposal?

**Comment by b3yond** [comment]
We are only speaking about the nbg instance, right? The images makes a lot less sense for other instances of course. Ticketfrei doesn't have influence over any of the other instances.

**Comment by git-sid** [comment]
I was referring to the nbg instance in particular. It would look much more serious if the banner image removed. We can then discuss which image to use as replacement. Do you agree?

**Comment by git-sid** [comment]
I think we should rethink the design in general, see #29

**Comment by git-sid** [comment]
Two options imo:

1. find a neutral wallpaper
2. randomize the wallpaper using something like [unsplash](https://unsplash.com/documentation#get-a-random-photo)

I'd prefer option 1. It's simple. But does a fitting image exist?
Option 2. circumvents this issue by loading a different image each refresh. There's more unnecessary overhead because of the loading of the image on every refresh. However, people couldn't argue that our bg image is ugly...

I'll propose to follow option 1 and try to find an fitting image.
Suggestions are always welcome.

**Comment by b3yond** [comment]
done.
