### ISSUE TITLE
Allude to ethics early in README

### ISSUE THREAD

**Issue by patcon** [ticketfrei/ticketfrei#70]
Thanks for this project!

I can imagine someone having misgivings about helping people skip fare. I personally think it's a great way to live prefiguratively in a world where public transit is not totally subsidized, but perhaps you have others reasons to believe in the approach of the project :)

Anyhow, I'm sure many many readers will be thinking through this as they read (and hopefully considering the validity of the tactic.

But perhaps we could make it more clear what the various short-form rationales might be. Obviously the README isn't the place for in-depth discussion, but simply addressing it and pointing elsewhere might make sense.

Are there any links or resources anyone could share that support this approach best?

**Comment by patcon** [comment]
Oh cool! Found the mission on website :) Will submit a PR

**Comment by b3yond** [comment]
oh, lol, that was indeed our own text :D but yeah, having that in the README is a good idea.
