### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by git-sid** [ticketfrei/ticketfrei#81]
We're currently using the ISC License.
Apparently, [GNU](https://www.gnu.org/licenses/license-list.html#ISC) itself recommends using a compatible license instead because of unclear wording in ISC.
Do you think this could be an issue?

**Comment by b3yond** [comment]
No, I don't think this will be a problem

**Comment by b3yond** [comment]
any objections against closing this issue? vmike either said that ISC is no problem

**Comment by git-sid** [comment]
perfect
