### ISSUE TITLE
Registration on Website fails – error 405

### ISSUE THREAD

**Issue by mastor1** [ticketfrei/ticketfrei#97]
**Expected behavior**
Signing up successfully on https://ticketfrei.links-tech.org/ to create a bot for my [city].

**Actual Behavior**
After clicking the confirmation link in my email app, the website says »Account already registered (please sign in)«, which is, obviously, not true. After signing in, the website returns »Error: 405 – Method Not Allowed – Sorry, the requested URL 'https://ticketfrei.links-tech.org/confirm/[city]/login' caused an error: –
Method not allowed.«

**To Reproduce**
1. Go to 'https://ticketfrei.links-tech.org/'
2. Sign up for your [city] under headline »How to get Ticketfrei to my city?«
3. Click confirmation link in your email app.
4. See error (already described above, under »Actual Behaviour«)

**Ticketfrei Version**
d60ec173cae72eafbba9f54ef05d770a72c26357

**Additional context**
I tried with different (vanilla) browsers and no security add-ons at all. Same behavior. I'm using a VPN, but this shouldn't matter.

**Comment by b3yond** [comment]
Hi, you got a wrong confirmation link, instead it should look like this: 
https://ticketfrei.links-tech.org/confirm/city/admupuwad89u98uq982mq2u09qu092q

When did you receive the confirmation mail, when did you click on the link?

**Comment by mastor1** [comment]
First time (already exactly thebehavior), yesterday at 21:15, clicked ~ 21:15.

**Comment by mastor1** [comment]
The link looked like your example.

**Comment by mastor1** [comment]
2nd try with different email and password: yesterday 21:37. Same error.

**Comment by b3yond** [comment]
okay... we're having an issue with our deployment right now. I'll get back to you as soon as that is sorted out, and then we can try to register an account again, I'd say.

**Comment by b3yond** [comment]
halleluja. it's fixed. So, can you try to register your city again, this time with lower case city name, so it doesn't throw an error?

**Comment by mastor1** [comment]
Yes, thanks!, I'll try it later and report.

**Comment by mastor1** [comment]
Works! Great job!

**Comment by b3yond** [comment]
Great :) Closed for now.
